config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "poses#index"
  get 'poses/search'

  resources :users, only: :show
  resources :poses, only: [:index, :new, :create, :destroy] do
    resource :likes, only: [:create, :destroy]
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/effect.rb
class Effect < ActiveHash::Base
  self.data = [
    { id: 1, name: '--' },
    { id: 2, name: 'Neck' },
    { id: 3, name: 'Shoulder' },
    { id: 4, name: 'Stomach' },
    { id: 5, name: 'Back' },
    { id: 6, name: 'Lower Back' },
    { id: 7, name: 'Buttock' },
    { id: 8, name: 'Legs' },
    { id: 9, name: 'Mind：Positive' },
    { id: 10, name: 'Mind：Calm Down' },
    { id: 11, name: 'Others' }
  ]

  include ActiveHash::Associations
  has_many :poses
end

app/models/intensity.rb
class Intensity < ActiveHash::Base
  self.data = [
    { id: 1, name: '--' },
    { id: 2, name: '★☆☆☆☆' },
    { id: 3, name: '★★☆☆☆' },
    { id: 4, name: '★★★☆☆' },
    { id: 5, name: '★★★★☆' },
    { id: 6, name: '★★★★★' }
  ]

  include ActiveHash::Associations
  has_many :poses
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :pose
  
  validates_uniqueness_of :pose_id, scope: :user_id
  # validates_uniqueness_ofによって、pose_idとuser_idの組が1組しかないようにバリデーションをかける。
end

app/models/pose.rb
class Pose < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :intensity
  belongs_to :effect

  belongs_to :user
  has_many :likes, dependent: :destroy
  # has_many :liked_users, through: :likes, source: :user
  # liked_usersによって投稿が誰にいいねされているのかを簡単に取得できるようになる。

  has_one_attached :image

  with_options presence: true do
    validates :title
    validates :minute
    validates :image
  end

  with_options numericality: { other_than: 1 } do
    validates :intensity_id
    validates :effect_id
  end

  validates :minute, numericality: { only_integer: true },
                     format: { with: /\A[0-9]\z/ }
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  enum gender: { male: 1, female: 2, others: 3, noanswer: 4 },
       age: { teens: 1, twenties: 2, thirties: 3, forties: 4, more: 5 }

  has_many :poses
  has_many :likes, dependent: :destroy
  # has_many :liked_poses, through: :likes, source: :pose
  # liked_posesによってuserがどの投稿をいいねしているのかを簡単に取得できるようになる。

  with_options presence: true do
    validates :nickname
    validates :password
    validates :gender
    validates :age
  end

  validates :password, format: { with: /\A(?=.*?[a-z])(?=.*?\d)[a-z\d]{6,}+\z/i, message: 'Include both letters and numbers' }

  def already_liked?(pose)
    self.likes.exists?(pose_id: pose.id)
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  private

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname, :gender, :age])
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController

  def create
    @like = current_user.likes.create(pose_id: params[:pose_id])
    redirect_back(fallback_location: root_path)
  end

  def destroy
    @pose = Pose.find(params[:pose_id])
    @like = Like.find_by(pose_id: params[:pose_id], user_id: current_user.id)
    @like.destroy
    redirect_back(fallback_location: root_path)
  end

end

app/controllers/poses_controller.rb
class PosesController < ApplicationController
  before_action :authenticate_user!, except: :index
  before_action :search_product, only: [:index, :search]
  before_action :pose_find, only: :destroy

  def index
    @poses = Pose.includes(:user).order('created_at DESC').page(params[:page]).per(6)
    set_pose_column
    @like = Like.new
  end

  def new
    @pose = Pose.new
  end

  def create
    @pose = Pose.new(pose_params)
    if @pose.save
      redirect_to "/users/#{current_user.id}"
    else
      render :new
    end
  end

  def search
    @results = @p.result.order('created_at DESC').page(params[:page]).per(10)
  end

  def destroy
    if current_user.id == @pose.user_id
      @pose.destroy
      redirect_to user_path
    else
      redirect_to user_path(@pose)
    end
  end

  private

  def pose_params
    params.require(:pose).permit(:title, :image, :effect_id, :minute, :intensity_id).merge(user_id: current_user.id)
  end

  def search_product
    @p = Pose.ransack(params[:q])  # 検索オブジェクトを生成
  end

  def set_pose_column
    @pose_title = Pose.select('title').distinct
    @pose_minute = Pose.select('minute').distinct
  end

  def pose_find
    @pose = Pose.find(params[:id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @nickname = current_user.nickname
    @poses = current_user.poses.order('created_at DESC').page(params[:page]).per(8)
  end

  def search
    @results = @p.result.order('created_at DESC')
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/poses_helper.rb
module PosesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Do Re: Me</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%# <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"> %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
     <script src="https://kit.fontawesome.com/484e6509e8.js" crossorigin="anonymous"></script>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/poses/_form.html.erb
<%= form_with model: pose, local: true do |f|%>
  <div class="field">
    <%= f.label :title, "ポーズの名前" %><br />
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <%= f.label :effect, "effect" %>
    <%= f.collection_select(:effect_id, Effect.all, :id, :name, {}, {class:"effect-select"}) %>
  </div>

  <div class="field">
    <%= f.label :minute, "Required Time (min）" %><br />
    <%= f.text_field :minute %>
  </div>

  <div class="field">
  <%= f.label :intensity, "Intensity  1 (Low) → 5 (High)" %>
  <%= f.collection_select(:intensity_id, Intensity.all, :id, :name, {}, {class:"intensity-select"}) %>
  </div>

  <div class="field">
    <%= f.label :image, "Pose Image" %><br />
    <%= f.file_field :image %>
  </div>

  <div class="actions">
    <%= f.submit "Post", class: :form__btn  %>
  </div>
<% end %>

app/views/poses/index.html.erb
<body>
<div id="wrap-all">
<%= render "shared/header" %>

<div class="main-content">
  <div class="main-left">
    <h3 class="main-left-title">New Posts</h3>
     <ul class="posts-wrapper">
        <% @poses.each do |pose| %>
        <li class="posted-item">

          <div class="pose-img-content">
            <%= image_tag pose.image, class: "pose__img"  %>
          </div>

          <div class="pose-detail">
           <p><span class="posted-pose-title"><%= pose.title %></p>
           <p><span class="posted-pose-detail">Effect : <%= pose.effect.name %></span></p>
           <p><span class="posted-pose-detail">Required Time : <%= pose.minute %> min</span></p>
           <p><span class="posted-pose-detail">Intensity : <%= pose.intensity.name %></span></p>

           
            <p>
           <% if user_signed_in? %>
            <% if current_user.already_liked?(pose) %>
              <%= link_to pose_likes_path(pose), method: :delete do %>
                <i class="fas fa-heart"></i>
              <% end %>
            <% else %>
              <%= link_to pose_likes_path(pose), method: :post do %> 
                <i class="far fa-heart"></i>
              <% end %>
            <% end %>
            <%= pose.likes.count %>
           <% else %>
            <p><i class="fas fa-heart"></i> <%= pose.likes.count %></p>
           <% end %>
           </p>

          </div>
          
         </li>
         <% end %>
       </ul>

         <div class="index-pagination">
           <%= paginate @poses %>
         </div>
  </div>

  <div class="main-right">
    <h3 class="main-right-title">Search</h3>
      <div class="search-item-select"> 
       <%= search_form_for @p, url: poses_search_path do |f| %>
        <%= f.label :title_eq, 'Pose Name :', class: "search-item-name"%>
        <%= f.collection_select :title_eq, @pose_title, :title, :title,  include_blank: 'Not Specified' %><br>
       <br>
        <%= f.label :effect_id_eq, 'Effect : ', class: "search-item-name" %>
        <%= f.collection_select :effect_id_eq, Effect.all, :id, :name,  include_blank: 'Not Specified' %><br>

        <%# <%= f.collection_check_boxes :effect_id_eq, Effect.all, :id, :name %>

       <br>
        <%= f.label :minute_lteq, 'Required Time : ', class: "search-item-name"  %>
        <%= f.collection_select :minute_lteq, @pose_minute, :minute, :minute,  include_blank: 'Not Specified' %><br>
       <br>
        <%= f.label :intensity_id_eq, 'Intensity : ', class: "search-item-name" %>
        <%= f.collection_select :intensity_id_eq, Intensity.all, :id, :name,  include_blank: 'Not Specified' %><br>
       <br>
        <%= f.submit 'Search' %>
       <% end %>
      </div>
  </div>

</div>
<%= render "shared/footer" %>
</div>
</body>

app/views/poses/new.html.erb
<body>
<div id="new-post-wrapper">

<header class='registration-page-header'>
  <div class='header-left'>
    Do Re: Me
  </div>

  <div class='header-right'>
    <%= link_to "My Page", "/users/#{current_user.id}", class: "user-nav-b" %>
    <%= link_to "Back to Top Page", root_path, class: "back-to-top" %>
  </div>

</header>


<div class="main">
  <div class="inner">
    <div class="form__wrapper">
      <h2 class="page-heading"> New Post</h2>
        <%# 部分テンプレートでフォームを表示する %>
      
 <%= form_with model: @pose, local: true do |f|%>
   <%# error-message表示 %>

    <% if @pose.errors.any? %>
     <div id="error_sentence">
     <h2><p style="color: red;"><%= pluralize(@pose.errors.count, "error") %> prohibited this post from being saved:</h2>

     <ul>
       <% @pose.errors.full_messages.each do |message| %>
          <li><% message %></li>
         <% end %>
      </ul>
      </div>
    <% end %>


  <div class="field">
    <%= f.label :title, "Pose Name" %><br />
    <%= f.text_field :title %>
     <% if @pose.errors.include?(:title) %>
       <p style="color: red;"><%= @pose.errors.full_messages_for(:title).first %>
     <% end %>
  </div>

  <div class="field">
    <%= f.label :effect, "Effect" %><br/>
    <%= f.collection_select(:effect_id, Effect.all, :id, :name, {}, {class:"effect-select"}) %>
    <% if @pose.errors.include?(:effect_id) %>
       <p style="color: red;"><%= @pose.errors.full_messages_for(:effect_id).first %>
     <% end %>
  </div>

  <div class="field">
    <%= f.label :minute, "Required Time (min）" %><br />
    <%= f.text_field :minute %>
    <% if @pose.errors.include?(:minute) %>
       <p style="color: red;"><%= @pose.errors.full_messages_for(:minute).first %>
       <p style="color: red;"><%= @pose.errors.full_messages_for(:minute).second %>
     <% end %>
  </div>

  <div class="field">
    <%= f.label :intensity, "Intensity" %><br/>
    <%= f.collection_select(:intensity_id, Intensity.all, :id, :name, {}, {class:"intensity-select"}) %>
    <% if @pose.errors.include?(:intensity_id) %>
       <p style="color: red;"><%= @pose.errors.full_messages_for(:intensity_id).first %>
     <% end %>
  </div>

  <div class="new-post-image-field">
    <%= f.label :image, "Upload Image", class: "image_input_btn"%> 
     <% if @pose.errors.include?(:image) %>
       <p style="color: red;"><%= @pose.errors.full_messages_for(:image).first %>
     <% end %>
       <div id="image-list">
       </div>
    <%= f.file_field :image, class: "default-image-form" %>
   
  </div>

  <div class="actions">
    <%= f.submit "Post", class: :form__btn  %>
  </div>
<% end %>

    </div>
  </div>
</div>



<footer>
<%= render "shared/footer" %>
</footer>

</div>
</body>

app/views/poses/search.html.erb
<body>
<div id="search-all-wrapper">

<header class='search-result-page-header'>
  <div class='header-left'>
    Do Re: Me
  </div>

  <div class='header-right'>
    <%= link_to "Back to Top Page", root_path, class: "back-to-top" %>
  </div>

</header>


<div class="search-result-main">
 <h4 class="search-result-title">Search Result</h4>

 <%# 検索結果の個数で条件分岐 %> 
 <% if @results.length !=0 %>
   <ul class="search-result-wrapper">
     <% @results.each do |result| %>
      <li class="found-item">
      
      <div class="found-item-img-content">
      <%= image_tag result.image, class: "search-item-img" %>
      </div>

      <div class="found-item-detail">

      <p><span class="found-item-title"><%= result.title %></p>
      Effect : <%= result.effect.name %>
      <br>
      Required Time : <%= result.minute %>  min
      <br>
      Intensity : <%= result.intensity.name %>
      <br>

      </div>

      </li>
     <% end %>
         
 <% else %>
    <div class="sorry-message">
     We are sorry!! The page you're looking for can't be found.
    </div>

         

   </ul>
 <% end %>


</div>
         <div class="search-pagination">
           <%= paginate @results %>
         </div>

<%= render "shared/footer" %>
</div>
</body>

app/views/shared/_background.html.erb
<div class="main-content">
</div>

app/views/shared/_footer.html.erb
<footer>
<div class='footer'>
  <div class='footer-contents'>
      © Do Re: Me
  </div>
</div>
</footer>

app/views/shared/_header.html.erb
<header class='index-page-header'>
 <div class='header-left'>
 Do Re: Me
 </div>

 <div class='header-right'>
   <% if user_signed_in? %>
          <div class="user_nav grid-6">
            <%= link_to "Log Out", destroy_user_session_path, method: :delete, class: "user-nav-b"  %>
            <%= link_to "My Page", "/users/#{current_user.id}", class: "user-nav-b" %>
          </div>
        <% else %>
          <div class='grid-6'>
            <%= link_to "Log In", new_user_session_path, class: "user-nav-a" %>
            <%= link_to "New Registration", new_user_registration_path, class: "user-nav-a" %>
          </div>
        <% end %>

 </div>
</header>

app/views/users/show.html.erb
<body>
<div id="wrap-all">

<header class='registration-page-header'>
  <div class='header-left'>
    Do Re: Me
  </div>

  <div class='header-right'>
    <%= link_to "New Post", new_pose_path, class: "user-nav-c" %>
    <%= link_to "Back to Top Page", root_path, class: "back-to-top" %>
  </div>
</header>


<div class="main-contents">

  <h3 class="room-title"><%= @nickname %>'s YOGA Room</h3>

  <ul class="pose-record">

       <% @poses.each do |pose| %>
       
        <li class="my-posted-item">

      <div class="my-record-img-content">
       <%= image_tag pose.image, class: "record-item-img" %>
      </div>

      <div class="my-record-detail">
             <div class="more">
              <span><%= image_tag 'arrow_top.png' %></span>
               <ul class="more_list">
                <li>
                <%= link_to 'Delete', pose_path(pose.id), method: :delete, data: { confirm: 'Delete this data from your room???' }%>
                </li>
               </ul>
             </div>
           <p><span id="my-record-title"><%= pose.title %></p>
           <p><span class="my-record-detail">Effect : <%= pose.effect.name %></span></p>
           <p><span class="my-record-detail">Intensity : <%= pose.intensity.name %></span></p>
           <p><span class="my-record-detail">Required Time : <%= pose.minute %> min</span></p>
           <p><i class="fas fa-heart"></i> <%= pose.likes.count %></p>

      </div>
        </li>

        <% end %>
  </ul>
         <div class="show-pagination">
           <%= paginate @poses %>
         </div>
</div>

<%= render "shared/footer" %>
</div>
</body>